version: '3.4'

services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.app:
    image: ${DOCKER_REGISTRY-}shoppingapp
    build:
      context: .
      dockerfile: Shopping.App/Dockerfile

  shopping.db:
    image: mongo