apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-api-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-api-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-app-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-app-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization