apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api-deployment
spec:
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
      - name: shopping-api
        image: kostaskpsacr.azurecr.io/shoppingapi:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.3"
          requests:
            memory: "64Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name:  MongoDBSettings__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: connection_string
      imagePullSecrets:
        - name:  acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
spec:
  selector:
    app: shopping-api
  ports:
  - port: 80
