apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: kostaskps/shoppingapp:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Shopping_API_Service_URL
          valueFrom:
            configMapKeyRef:
              name: shoppingapi-configmap
              key: shopping_api_url
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
spec:
  type: NodePort
  selector:
    app: shopping-app
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30000